apply plugin: 'com.android.application'

android {
    namespace 'com.zeei.penyegaran'
    compileSdkVersion 34
    defaultConfig {
        applicationId "com.zeei.penyegaran"
        minSdkVersion 23
        targetSdkVersion 34
        versionCode 3
        versionName "3"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.gms:play-services-ads:24.3.0'
    implementation 'com.google.android.ump:user-messaging-platform:3.2.0'

    implementation 'com.android.volley:volley:1.2.1'
    implementation 'com.google.android.material:material:1.12.0'

    implementation("com.unity3d.ads:unity-ads:4.14.2")
    implementation("com.google.ads.mediation:unity:4.14.2.0")
}
